const ActionTypes = {
    /*
    * Action Constants
    */
    USER_LOGOUT: 'USER_LOGOUT',
    BATCH: 'BATCHING_REDUCER.BATCH',

    // TSCS
    REQUEST_TSCS: 'REQUEST_TSCS',
    RECEIVE_TSCS: 'RECEIVE_TSCS',
    ADD_TSCS: 'ADD_TSCS',
    EDIT_TSCS: 'EDIT_TSCS',
    DELETE_TSCS: 'DELETE_TSCS',

    TOGGLE_TSCS_DELETE_MODAL: 'TOGGLE_TSCS_DELETE_MODAL',
    TOGGLE_TSCS_MODAL: 'TOGGLE_TSCS_MODAL',

    // Portfolio
    SELECT_TAB: 'SELECT_TAB',
    SELECT_DISPLAY_CURRENCY: 'SELECT_DISPLAY_CURRENCY',
    SELECT_DISPLAY_ACCOUNT: 'SELECT_DISPLAY_ACCOUNT',
    SHOW_ZERO_SHARE_HOLDING: 'SHOW_ZERO_SHARE_HOLDING',
    SET_START_DATE: 'SET_START_DATE',
    SET_END_DATE: 'SET_END_DATE',

    // Quote
    REQUEST_QUOTES: 'REQUEST_QUOTES',
    REQUEST_QUOTES_TIMEOUT: 'REQUEST_QUOTES_TIMEOUT',
    RECEIVE_SINGLE_QUOTE: 'RECEIVE_SINGLE_QUOTE',
    RECEIVE_QUOTES: 'RECEIVE_QUOTES',
    SET_QUOTE_DISPLAY_DATE: 'SET_QUOTE_DISPLAY_DATE',
    REQUEST_HISTORICAL_QUOTES: 'REQUEST_HISTORICAL_QUOTES',
    RECEIVE_HISTORICAL_QUOTES: 'RECEIVE_HISTORICAL_QUOTES',
    SET_USE_HISTORICAL_QUOTE: 'SET_USE_HISTORICAL_QUOTE',
    TOGGLE_QUOTE_MODAL: 'TOGGLE_QUOTE_MODAL',

    REQUEST_CURRENCY: 'REQUEST_CURRENCY',
    REQUEST_CURRENCY_TIMEOUT: 'REQUEST_CURRENCY_TIMEOUT',
    RECEIVE_CURRENCY: 'RECEIVE_CURRENCY',

    REQUEST_SYMBOLS: 'REQUEST_SYMBOLS',
    RECEIVE_SYMBOLS: 'RECEIVE_SYMBOLS',

    UPDATE_BALANCE_PERCENTAGE: 'UPDATE_BALANCE_PERCENTAGE',
    UPDATE_BALANCE_LABEL: 'UPDATE_BALANCE_LABEL',

    REQUEST_ALLOCATIONS: 'REQUEST_ALLOCATIONS',
    RECEIVE_ALLOCATIONS: 'RECEIVE_ALLOCATIONS',
    ADD_ALLOCATIONS: 'ADD_ALLOCATIONS',
    DELETE_ALLOCATIONS: 'DELETE_ALLOCATIONS',

    REQUEST_SIGNUP: 'REQUEST_SIGNUP',
    RECEIVE_SIGNUP: 'RECEIVE_SIGNUP',
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    RECEIVE_LOGIN: 'RECEIVE_LOGIN',
    CLEAR_LOGIN_ERROR: 'CLEAR_LOGIN_ERROR',
    CLEAR_SIGNUP_ERROR: 'CLEAR_SIGNUP_ERROR',
};

export default ActionTypes;