/*
 * Action Constants
 */
export const USER_LOGOUT = 'USER_LOGOUT';
export const BATCH = 'BATCHING_REDUCER.BATCH';

export const REQUEST_TSCS = 'REQUEST_TSCS';
export const RECEIVE_TSCS = 'RECEIVE_TSCS';
export const ADD_TSCS = 'ADD_TSCS';
export const DELETE_TSCS = 'DELETE_TSCS';

export const OPEN_TSCS_FORM = 'OPEN_TSCS_FORM';
export const CLOSE_TSCS_FORM = 'CLOSE_TSCS_FORM';

// Portfolio
export const SELECT_TAB = 'SELECT_TAB';
export const SELECT_DISPLAY_CURRENCY = 'SELECT_DISPLAY_CURRENCY';
export const SHOW_ZERO_SHARE_HOLDING = 'SHOW_ZERO_SHARE_HOLDING';

export const REQUEST_QUOTES = 'REQUEST_QUOTES';
export const RECEIVE_QUOTES = 'RECEIVE_QUOTES';

export const REQUEST_CURRENCY = 'REQUEST_CURRENCY';
export const RECEIVE_CURRENCY = 'RECEIVE_CURRENCY';

export const REQUEST_SYMBOLS = 'REQUEST_SYMBOLS';
export const RECEIVE_SYMBOLS = 'RECEIVE_SYMBOLS';

export const UPDATE_BALANCE_PERCENTAGE = 'UPDATE_BALANCE_PERCENTAGE';
export const UPDATE_BALANCE_LABEL = 'UPDATE_BALANCE_LABEL';

export const REQUEST_ALLOCATIONS = 'REQUEST_ALLOCATIONS';
export const RECEIVE_ALLOCATIONS = 'RECEIVE_ALLOCATIONS';
export const ADD_ALLOCATIONS = 'ADD_ALLOCATIONS';
export const DELETE_ALLOCATIONS = 'DELETE_ALLOCATIONS';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const RECEIVE_SIGNUP = 'RECEIVE_SIGNUP';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const CLEAR_SIGNUP_ERROR = 'CLEAR_SIGNUP_ERROR';
