/*
 * Action Constants
 */
export const REQUEST_TSCS = 'REQUEST_TSCS';
export const RECEIVE_TSCS = 'RECEIVE_TSCS';
export const ADD_TSCS = 'ADD_TSCS';
export const DELETE_TSCS = 'DELETE_TSCS';
export const OPEN_TSCS_FORM = 'OPEN_TSCS_FORM';
export const CLOSE_TSCS_FORM = 'CLOSE_TSCS_FORM';
export const SELECT_TAB = 'SELECT_TAB';
export const SELECT_DISPLAY_CURRENCY = 'SELECT_DISPLAY_CURRENCY';
export const REQUEST_QUOTES = 'REQUEST_QUOTES';
export const RECEIVE_QUOTES = 'RECEIVE_QUOTES';
export const REQUEST_CURRENCY = 'REQUEST_CURRENCY';
export const RECEIVE_CURRENCY = 'RECEIVE_CURRENCY';
export const REQUEST_SYMBOLS = 'REQUEST_SYMBOLS';
export const RECEIVE_SYMBOLS = 'RECEIVE_SYMBOLS';